In [2]:
import numpy as np 


In [3]:
arr = np.array([0,1,2,3,4,5,6])
sliced_arr_1 = arr[2:5]
print(sliced_arr_1)

sliced_arr_2 = arr[::2]
print(sliced_arr_2)

sliced_arr_3 = arr[-2:]
print(sliced_arr_3)

sliced_arr_4 = arr[::-1]
print(sliced_arr_4)

[2 3 4]
[0 2 4 6]
[5 6]
[6 5 4 3 2 1 0]


In [4]:
arr_2d = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(arr_2d)


sliced_arr2d_1 = arr_2d[1, 1:2]
print(sliced_arr2d_1)

sliced_arr2d_2 = arr_2d[1:3, 1]
print(sliced_arr2d_2)

sliced_arr2d_3 = arr_2d[1:, 1:]
print(sliced_arr2d_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[4]
[4 7]
[[4 5]
 [7 8]]


In [5]:
arr_1 = np.array([1,2,3,4,5,6])
arr_copy = arr_1.copy()
arr_copy[2] = 99
print(arr_1)
print(arr_copy)

[1 2 3 4 5 6]
[ 1  2 99  4  5  6]


In [6]:
arr_1_d = np.array((1,2,3,4))
print(arr_1_d.shape)

arr_2_d = np.array(((1,2,3,4,5), (6,7,8,9,0)))
print(arr_2_d.shape)

(4,)
(2, 5)


In [7]:
arr_re = np.array([1,2,3,4,5,6])
reshaped_ar = arr_re.reshape((2,3))
# print(arr_re)
# print(reshaped_arr)
# print(reshaped_arr.shape)

In [8]:
arr_re.resize((3,3))
print(arr_re)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [9]:
arr = np.array([1,2,3,4])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[1 3]


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,88])
filter_arr = arr > 5 
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 88]


In [12]:
A = np.array([1,2,3])
B = np.array([4,5,6,7])

print(A**2)
print(A+B)
print(A - B)


[1 4 9]


ValueError: operands could not be broadcast together with shapes (3,) (4,) 