In [1]:
even_squares = [x**2 for x in range(10) if x % 2 == 0]
print(even_squares)

[0, 4, 16, 36, 64]


In [2]:
even_squares1 = list(x**2 for x in range(10) if x % 2 == 0)
print(even_squares1)

[0, 4, 16, 36, 64]


In [3]:
numbers = [1,2,3,4,5]
modified_numbers = [x**2 if x % 2 == 0 else x + 1 for x in numbers]
print(modified_numbers)

[2, 4, 4, 16, 6]


In [4]:
numbers1 = [1,2,3,4,5]
modified_numbers1 = [x**2 for x in numbers1 if x % 2 == 0 else x + 1]
print(modified_numbers1)

SyntaxError: invalid syntax (325093019.py, line 2)

In [ ]:
matrix = [[1,0,0],
          [0,1,0],
          [0,0,1]]
print(matrix)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [ ]:
matrix1 = []
for i in range(3):
    row = []
    for j in range(3):
        if i == j:
            row.append(1)
        else:
            row.append(0)
    matrix1.append(row)
print(matrix1)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [ ]:
identity_matrix = [[1 if i==j else 0 for j in range(3)] for i in range(3)]
print(identity_matrix)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [ ]:
import numpy as np 
identity_matrix1 = np.eye(3)
print(identity_matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
add_numbers = lambda x, y : x + y 
result_numbers = add_numbers(1,2)
print(result_numbers) 

3


In [ ]:
numbers_list = [10,20,30]
add_list = lambda x : sum(x)
print(add_list(numbers_list))

60


In [ ]:
words = ["apple", "banana", "kiwi", "strawberry", "orange",""]
longest_fruit = max(words, key = lambda x : len(x))
print("longest word is " + longest_fruit)

longest word is strawberry


In [ ]:
word = max(words)
print(word) 

strawberry


In [ ]:
people = [
    {"name" : "Alice", "age" : 30},
    {"name" : "Bob", "age" : 45},
    {"name": "Charlie", "age" : 35}
]
oldest_person = max(people, key = lambda x : x["age"])  
# above print the whole dict whose age is max
print(oldest_person)
print(type(oldest_person))
print(oldest_person["name"])

{'name': 'Bob', 'age': 45}
<class 'dict'>
Bob


In [ ]:
array_in_np = np.array([1,2,3])
array1 = np.array((4,5,6,7))
print(array_in_np)
print(array1)
print(type(array_in_np))
print(type(array1))

[1 2 3]
[4 5 6 7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
zero_array = np.array(10)
print(zero_array)

one_d_array = np.array([1,2,3,4,5])
print(one_d_array)

two_d_array = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(two_d_array)

three_d_array = np.array([[[1,2,3,4,5],[2,4,68,65,44]],[[33,4,6,7,99],[1,2,3,4,5]]])
print(three_d_array)

10
[1 2 3 4 5]
[[1 2 3 4 5]
 [5 6 7 8 9]]
[[[ 1  2  3  4  5]
  [ 2  4 68 65 44]]

 [[33  4  6  7 99]
  [ 1  2  3  4  5]]]


In [ ]:
print(zero_array.ndim)
print(three_d_array.ndim)

0
3


In [ ]:
print(two_d_array)
print(two_d_array[0,1])


[[1 2 3 4 5]
 [5 6 7 8 9]]
2


In [ ]:
print(zero_array.dtype)

int32
