- ### NumPy (short for Numerical Python) is the fundamental package for scientific computing in Python. 
- ### Main reference: NumPy User Guide Release 1.18.4 written by the NumPy community.
- ### It is a Python library that is used to work with arrays by providing a multidimensional array object (ndarray object are n-dimensional arrays of homogeneous data types) and performs various mathematical operations on them. 
- ### NumPy is extremely useful in making calculations and data analysis in Python.
- ### There are several important differences between NumPy arrays and the standard Python sequences (list datatypes)
  - #### NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
  - #### The elements in a NumPy array are all required to be of the same data type.
  - #### NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
- ### NumPy is not in-built in Python and we load/import the NumPy library (standard to use 'np' as a short name).

In [10]:
import numpy as np

### NumPy Array
- ### We can create a NumPy ndarray object by using the array() function. array is not inbuilt and we have to call it by writing np.array() (otherwise we will get name error).
- ### Elements of a NumPy array can be assigned using a list or tuple.

In [11]:
array_1= np.array([1, 3, 5])
array_2= np.array((2, 4, 6))
print(array_1)
print(array_2)

[1 3 5]
[2 4 6]


In [12]:
#The two arrays above appears like list but the are of numpy.ndarray array data types.
print(type(array_1))
print(type(array_2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
#A dimension in arrays is one level of array depth (nested arrays).
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
zero_d_array= np.array(10)
print('zero_d_array', zero_d_array)
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
one_d_array= np.array([1,2,3])
print('one_d_array', one_d_array)
#An array that has 1-D arrays as its elements is called a 2-D array.These are often used to represent matrix.
two_d_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('two_d_array', two_d_array)
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
three_d_array = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]] )
print('three_d_array', three_d_array)

zero_d_array 10
one_d_array [1 2 3]
two_d_array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
three_d_array [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [14]:
#arrayname.ndim returns the number of dimensions of an array.
print(zero_d_array.ndim)
print(one_d_array.ndim)
print(two_d_array.ndim)
print(three_d_array.ndim)

0
1
2
3


In [15]:
#NumPy arrays are indexed like lists.
print(one_d_array)
print(one_d_array[2])

[1 2 3]
3


In [16]:
print(two_d_array)
print(two_d_array[0, 1]) #this is different from lists: [0][1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [17]:
#arrayname.dtype returns the data type of the array.
print(zero_d_array.dtype)
print(one_d_array.dtype)
print(two_d_array.dtype)
print(three_d_array.dtype)
float_array= np.array([(1.2,2.3,3.4)])
print(float_array.dtype)

int32
int32
int32
int32
float64


In [18]:
#Array slicing: extract a portion of an array or create views on the original array without copying data.
# syntax for 1-d array: [start_index:end_index:step]
#start_index and end_index are zero, and step is 1 by default (if unspecified).
arr = np.array([0, 1, 2, 3, 4, 5])
sliced_arr_1 = arr[2:5]  # Elements from index 2 to 4
print(sliced_arr_1)
sliced_arr_2 = arr[:5]  # Elements from index 0 to 4
print(sliced_arr_2)
sliced_arr_3 = arr[2:]  # Elements from index 2 to the last item
print(sliced_arr_3)
sliced_arr_4 = arr[:]  # All Elements from start to end index
print(sliced_arr_4)
sliced_arr_5 = arr[::2]  # every second item from start to end as the step is 2 and start and end are unspecified.
print(sliced_arr_5) 
sliced_arr_6 = arr[-2:]  # last 2 Elements using the negative index -2 for the second last item.
print(sliced_arr_6)

[2 3 4]
[0 1 2 3 4]
[2 3 4 5]
[0 1 2 3 4 5]
[0 2 4]
[4 5]


In [19]:
arr_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print("given array",arr_2d) 
print("items at index 1 and 2 of the second element",arr_2d[1, 1:3]) #returns 1-d array
print("items at index 1 of second and third element",arr_2d[1:3, 1]) #returns 1-d array
print("items at index 1 onwards for elements at index one onwards",arr_2d[1:, 1:]) #returns 2-d array; Rows from index 1 onwards, columns from index 1 onwards

given array [[0 1 2]
 [3 4 5]
 [6 7 8]]
items at index 1 and 2 of the second element [4 5]
items at index 1 of second and third element [4 7]
items at index 1 onwards for elements at index one onwards [[4 5]
 [7 8]]


In [20]:
#we can use indexing to modify a given array.
arr[2]=100
print(arr)
arr_2d[1,2]=100
print(arr_2d)

[  0   1 100   3   4   5]
[[  0   1   2]
 [  3   4 100]
 [  6   7   8]]


In [21]:
# Making copy of an array: A copy is a new array with a new memory location that is completely independent of the original array.
# .copy() or np.copy(arrayname)methods copies an array to another variable. 
# Modifications to the copied array do not affect the original array, and vice versa.
arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()
arr_copy[2] = 99
print("original array", arr)        # Original array is not affected
print("modified copy of the original", arr_copy)   # Copied array is modified

original array [1 2 3 4 5]
modified copy of the original [ 1  2 99  4  5]


In [22]:
# View of an array in NumPy: A view is a new array that refers to the same data as the original array.
# Unlike copy, modifications to the view array affect the original array, and vice versa.
# slicing or .view() methods creates array views.
print(arr)
arr_view_1 = arr[1:4]  # Creates a view
arr_view_2=arr.view()
arr_view_1[1] = 100
arr_view_2[3]=50
print(arr)        # Original array is modified
print(arr_view_1)   # View is also modified
print(arr_view_2)

[1 2 3 4 5]
[  1   2 100  50   5]
[  2 100  50]
[  1   2 100  50   5]


In [23]:
# To check if an array is a copy or a view, we can use arrayname.base command
print(arr_copy.base)  # copy returns None (copy)
print(arr_view_2.base)  # view returns the original array 

None
[  1   2 100  50   5]


In [24]:
# Alternatively, flags.owndata attribute provides information whether the array owns its data or is a view.
print(arr_copy.flags.owndata)  # True (A copy owns its data and doesn't affect the original array)
print(arr_view_1.flags.owndata)  # False (A view doesn't own its data)

True
False


In [25]:
#shape of an array: number of items in each dimension.
#The .shape() attribute of a NumPy array provides a tuple representing the size of each dimension.
arr_1_d=np.array((1, 2, 3))
print(arr_1_d.shape )        # A 1D array has a shape tuple with one element. Output(3,)      
arr_2_d = np.array([[1, 2, 3], [4, 5, 6]]) #the array has 2 dimensions, where the first dimension has 2 elements and the second has 3.
print(arr_2_d.shape)  # A 2D array has a shape tuple with two elements representing rows and columns. Output: (2, 3) - 2 rows, 3 columns


(3,)
(2, 3)


In [26]:
# Changing the Shape: reshape() method creates a new array with a different shape but the same data.
#reshaping alters the number of dimensions and adjust the quantity of elements within each dimension.
#while reshaping we need to ensure that the product of the dimensions is equal to the total number of items.
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print(arr)
print(reshaped_arr)
print(reshaped_arr.shape)  # Output: (2, 3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [27]:
#reshaping creates a view and not a copy.
#Check if the returned array is a copy or a view
print(reshaped_arr.base)
print(reshaped_arr.flags.owndata)

[1 2 3 4 5 6]
False


In [28]:
#The resize function modifies the shape of an array in-place. 
#If the new size is larger, it add zeros as elements; if smaller, it truncates elements.
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)
print(arr.shape)  # Output: (2, 3)
arr.resize((3, 3))
print(arr)
print(arr.shape) 

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [0 0 0]]
(3, 3)


In [29]:
#The .flatten() method returns a 1D array containing the same data. 
#It effectively collapses all dimensions into one dimension.
#alternative command is .reshape(-1)
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
#flattened_arr = arr.reshape(-1)
print(flattened_arr)
print(flattened_arr.shape)


[1 2 3 4 5 6]
(6,)


In [30]:
#Transposing a 2-D array swaps its rows and columns.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_transpose= arr.transpose()
print(arr_transpose)
print(arr_transpose.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [31]:
#Joining means putting contents of two or more arrays in a single array.
#NumPy joins arrays by axes
#.concatenate() function is used to join arrays.
arr1 = np.array([1, 3, 5])

arr2 = np.array([2, 4, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 3 5 2 4 6]


In [32]:
#joining a 2-d arrray
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [33]:
#Splitting is reverse operation of Joining.
#Splitting breaks one array into multiple.
#array_split() splits an array, we pass it the array we want to split and the number of splits.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(type(newarr)) #The return value is a list containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [34]:
#If the array has less elements than required, it will adjust from the end accordingly.
newarr_1 = np.array_split(arr, 4)
print(newarr_1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [35]:
#Split a 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [36]:
newarr = np.array_split(arr, 2, axis=1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [37]:
# searching in an array.
#where() method searches an array for a certain value, and return the indexes that get a match.
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [38]:
# we can provide conditional statements in where() method. Ex: Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [39]:
# sorting arrays using np.sort(arrayname)
arr = np.array([5, 3, 0, 1, 2])

print(np.sort(arr))


[0 1 2 3 5]


In [40]:
sorted_arr_reverse = np.sort(arr)[::-1]
print(sorted_arr_reverse)

[5 3 2 1 0]


In [41]:
#Filtering Arrays: Getting some elements out of an existing array and creating a new array out of them is called filtering.
#In NumPy, we can filter an array using a boolean index list.
#A boolean index list is a list of booleans corresponding to indexes in the array.
#If the value at an index is True that element is contained in the filtered array.
#if the value at that index is False that element is excluded from the filtered array.
arr = np.array([1, 2, 3, 4])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[1 3]


In [42]:
#In the example above we hard-coded the True and False values.
#but the common use is to create a filter array based on conditions.
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = arr > 5

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [43]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = arr%2==1
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[ True False  True False  True False  True False  True False]
[1 3 5 7 9]


In [44]:
#basic operations: (Arrays dimensions needs to be same)
#1-D arrays
A= np.array([1, 2, 3])
B= np.array((4, 5, 6))
print(A**2)
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A%B)
print(B//A)

[1 4 9]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[4 2 2]


In [64]:
A= np.array([1, 2, 3])
B= np.array((4, 5, 6,7))
print(A+B)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [45]:
#Basic operations on 2 D arrays:
C= np.array([[1, 2, 3], [4, 5, 6]])
D= np.array([[7, 8, 9], [10, 11, 12]])
print(C+D)
print(C-D)
print(C*D)
print(C/D)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [46]:
#Universal functions in NumPy
# add(array1, array2) adds corresponding items in two arrays or lists. 
list1=[1,2,3]
print(type(list1))
list2=[4,5,6]
print(np.add(list1,list2))
print(type(np.add(list1,list2)))
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.add(arr1,arr2))
print(type(np.add(arr1,arr2)))

<class 'list'>
[5 7 9]
<class 'numpy.ndarray'>
[5 7 9]
<class 'numpy.ndarray'>


In [47]:
#similarly, we have subtract, multiply, divide, power, mod, remainder, absolute
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.multiply(arr1,arr2))

[ 4 10 18]


In [48]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
print(np.add(arr1, arr3))

[ 8 10 12]


In [49]:
#set operations in numpy: unique, union, intersection, setdifference, etc.
print(np.unique(np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7]))) #unique() returns unique elements from any 1-D array
arr_1= np.array([1,1,2,3,4,4])
arr_2=np.array([1,2,5,6])
arr_union= np.union1d(arr_1,arr_2)
print("Union:", arr_union)
arr_intersection=np.intersect1d(arr_1,arr_2)
print("Intersection:",arr_intersection)
arr_diff=np.setdiff1d(arr_1,arr_2)
print("Difference:",arr_diff)


[1 2 3 4 5 6 7]
Union: [1 2 3 4 5 6]
Intersection: [1 2]
Difference: [3 4]


In [50]:
#Dot product of vectors:
vector_1= np.array([1, 2, 3])
vector_2=np.array([4,5,6])
print(np.dot(vector_1, vector_2)) #dot product of arrays/vectors

32


In [51]:
#some common statistical operations
A = np.array([1, 3, 5, 7, 9])
print(np.mean(A))
print(np.median(A))
print(np.std(A))
print(np.var(A))

5.0
5.0
2.8284271247461903
8.0


In [52]:
#Using min max functions for filtering arrays
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.min())
print("minimum among columns",arr.min(axis=1))
print("max among columns",np.max(arr, axis=1))
print(np.sum(arr, axis=0))
print(np.product(arr))

[[1 2 3]
 [4 5 6]]
1
minimum among columns [1 4]
max among columns [3 6]
[5 7 9]
720


In [53]:
#Some common mathemeatical operations:
print(np.sqrt(100)) #Square root
print(np.exp(1)) #Exponential
print(np.log(1)) #Logarithm with the base e
print(np.log10(10)) #Logarithm with the base 10

10.0
2.718281828459045
0.0
1.0


In [54]:
#defining higher dimension arrays
arr = np.array([1, 2, 3], ndmin=4)

print(arr)
print('number of dimensions :', arr.ndim)
print("shape",arr.shape)

[[[[1 2 3]]]]
number of dimensions : 4
shape (1, 1, 1, 3)


In [55]:
#Values count
arr = np.array([1, 2, 3], ndmin=4)
arr_2D = np.array([[1, 2, 3],[4,5,6]])
print(arr)
print(arr_2D)
print(arr.size)
print(arr_2D.size)

[[[[1 2 3]]]]
[[1 2 3]
 [4 5 6]]
3
6


In [56]:
#Creating Array with 0 and 1: np.zeros() and np.ones()
print(np.zeros(3, dtype=int))
print(np.ones(1))
print(np.zeros((2,3)))

[0 0 0]
[1.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
#creating sequences: np.arrange(start, end, interval)
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [58]:
#creating arithmetic sequences with specified no. of items:
print(np.linspace(0,20,5, endpoint= True, dtype=int))

[ 0  5 10 15 20]


In [59]:
# generating arrays with random number using the random module in NumPy
random_test_1 = np.random.randint(10)
print(random_test_1)
random_test_2 = np.random.randint(10, size=3)
print(random_test_2)
random_test_3 = np.random.rand() #Generate a random float between 0 and 1
print(random_test_3)
random_test_4 = np.random.rand(3) #Generate a random float array of size three with values between 0 and 1
print(random_test_4)

5
[7 0 7]
0.14738517484659897
[0.60703389 0.74142314 0.69034484]


In [60]:
#creating arrays with random values: np.random.randn()
random_array=np.random.randn(5)
print(random_array)


[ 0.06881966 -1.54054845 -0.70033591  0.18424204  0.82161279]


In [61]:
#random 2-D array with three elements: shape 2X3
print(np.random.randn(2, 3))
print(np.random.randint(10, size=(2,3)))
print(np.random.rand(2,3))

[[-0.18426194 -0.72826676  0.62424149]
 [-0.22590893  2.24833884  0.2285751 ]]
[[0 5 3]
 [2 5 9]]
[[0.46615284 0.51319463 0.63705125]
 [0.01155146 0.73650662 0.73144497]]


In [62]:
#generating random array from choice of an array
arr= np.random.choice([1, 2, 3, 4])
print(arr)
arr_2=np.random.choice([5, 6, 7, 8], size=(2,3))
print(arr_2)

3
[[7 6 7]
 [8 5 7]]


In [63]:
print(np.random.randint(low= 1, high= 10, size=10)) #creates a 1-D array of 10 items with values ranging from low(including) and high (excluding)

[5 2 5 2 1 4 5 7 9 8]
